<?php

namespace App\Controller;

use DateTime;
use App\Entity\Cards;
use App\Entity\Games;
use App\Entity\Users;
use App\Entity\Situation;
use PhpParser\Builder\Declaration;
use App\GameClasses\DrawInStack\Draw;
use App\GameClasses\ToolsGame\ToolsGame;
use App\GameClasses\TrickGame\TrickGame;
use Doctrine\ORM\EntityManagerInterface;
use App\GameClasses\ImportanceCards\Score;
use App\GameClasses\ImportanceCards\Value;
use App\GameClasses\ComputerPlay\ComputerPlay;
use App\GameClasses\Declarations\Declarations;
use Symfony\Component\Routing\Annotation\Route;
use App\GameClasses\ImportanceCards\Consequences;
use App\GameClasses\ComputerPlay\ComputerPlayEndGame;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;



class TestController extends AbstractController
{
    /**
     * render the home page.
     * 
     * @Route("/test", name="test")
     * 
     * @return Response
    */
    public function test()
    {
        $Consequences = new Consequences;
        $data = [
            'init' => true,
            'playFirst' => 'player',
            'stage' => 'play',
            'trump' => [
                'name' => 'sevenSpades',
                'number' => 7,
                'suit' => 'spade',
                'rank' => 1,
                'twinCardNumber' => 3,
                'img' => '/images/svg/7_of_spades.svg',
                'score' => 1,
            ],
            'stack' => [
                [
                    'name' => 'nineDiamonds',
                    'number' => 17,
                    'suit' => 'diamond',
                    'rank' => 3,
                    'twinCardNumber' => 21,
                    'img' => '/images/svg/9_of_diamonds.svg',
                    'score' => 13,
                ],
                [
                    'name' => 'queenDiamonds',
                    'number' => 45,
                    'suit' => 'diamond',
                    'rank' => 5,
                    'twinCardNumber' => 41,
                    'img' => '/images/svg/queen_of_diamonds.svg',
                    'score' => 15,
                ],
                [
                    'name' => 'nineHearts',
                    'number' => 18,
                    'suit' => 'heart',
                    'rank' => 3,
                    'twinCardNumber' => 22,
                    'img' => '/images/svg/9_of_hearts.svg',
                    'score' => 3,
                ],
                [
                    'name' => 'nineSpades',
                    'number' => 19,
                    'suit' => 'spade',
                    'rank' => 3,
                    'twinCardNumber' => 23,
                    'img' => '/images/svg/9_of_spades.svg',
                    'score' => 3,
                ],
                [
                    'name' => 'nineClubs',
                    'number' => 20,
                    'suit' => 'club',
                    'rank' => 3,
                    'twinCardNumber' => 24,
                    'img' => '/images/svg/9_of_clubs.svg',
                    'score' => 3,
                ],
                [
                    'name' => 'nineDiamonds',
                    'number' => 21,
                    'suit' => 'diamond',
                    'rank' => 3,
                    'twinCardNumber' => 17,
                    'img' => '/images/svg/9_of_diamonds.svg',
                    'score' => 13,
                ],
                [
                    'name' => 'nineHearts',
                    'number' => 22,
                    'suit' => 'heart',
                    'rank' => 3,
                    'twinCardNumber' => 18,
                    'img' => '/images/svg/9_of_hearts.svg',
                    'score' => 3
                ],
                [
                    'name' => 'nineSpades',
                    'number' => 23,
                    'suit' => 'spade',
                    'rank' => 3,
                    'twinCardNumber' => 19,
                    'img' => '/images/svg/9_of_spades.svg',
                    'score' => 3
                ],
                [
                    'name' => 'nineClubs',
                    'number' => 24,
                    'suit' => 'club',
                    'rank' => 3,
                    'twinCardNumber' => 20,
                    'img' => '/images/svg/9_of_clubs.svg',
                    'score' => 3,
                ],
                [
                    'name' => 'jackDiamonds',
                    'number' => 33,
                    'suit' => 'diamond',
                    'rank' => 4,
                    'twinCardNumber' => 37,
                    'img' => '/images/svg/jack_of_diamonds.svg',
                    'score' => 14,
                ],
                [
                    'name' => 'jackHearts',
                    'number' => 34,
                    'suit' => 'heart',
                    'rank' => 4,
                    'twinCardNumber' => 38,
                    'img' => '/images/svg/jack_of_hearts.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'jackClubs',
                    'number' => 36,
                    'suit' => 'club',
                    'rank' => 4,
                    'twinCardNumber' => 40,
                    'img' => '/images/svg/jack_of_clubs.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'jackDiamonds',
                    'number' => 37,
                    'suit' => 'diamond',
                    'rank' => 4,
                    'twinCardNumber' => 33,
                    'img' => '/images/svg/jack_of_diamonds.svg',
                    'score' => 14,
                ],
                [
                    'name' => 'jackHearts',
                    'number' => 38,
                    'suit' => 'heart',
                    'rank' => 4,
                    'twinCardNumber' => 34,
                    'img' => '/images/svg/jack_of_hearts.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'jackClubs',
                    'number' => 40,
                    'suit' => 'club',
                    'rank' => 4,
                    'twinCardNumber' => 36,
                    'img' => '/images/svg/jack_of_clubs.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'queenHearts',
                    'number' => 42,
                    'suit' => 'heart',
                    'rank' => 5,
                    'twinCardNumber' => 46,
                    'img' => '/images/svg/queen_of_hearts.svg',
                    'score' => 5,
                ],
                [
                    'name' => 'queenSpades',
                    'number' => 43,
                    'suit' => 'spade',
                    'rank' => 5,
                    'twinCardNumber' => 47,
                    'img' => '/images/svg/queen_of_spades.svg',
                    'score' => 5
                ],
                [
                    'name' => 'queenClubs',
                    'number' => 44,
                    'suit' => 'club',
                    'rank' => 5,
                    'twinCardNumber' => 48,
                    'img' => '/images/svg/queen_of_clubs.svg',
                    'score' => 5,
                ],
                [
                    'name' => 'queenHearts',
                    'number' => 46,
                    'suit' => 'heart',
                    'rank' => 5,
                    'twinCardNumber' => 42,
                    'img' => '/images/svg/queen_of_hearts.svg',
                    'score' => 5,
                ],
                [
                    'name' => 'queenSpades',
                    'number' => 47,
                    'suit' => 'spade',
                    'rank' => 5,
                    'twinCardNumber' => 43,
                    'img' => '/images/svg/queen_of_spades.svg',
                    'score' => 5,
                ],
                [
                    'name' => 'queenClubs',
                    'number' => 48,
                    'suit' => 'club',
                    'rank' => 5,
                    'twinCardNumber' => 44,
                    'img' => '/images/svg/queen_of_clubs.svg',
                    'score' => 5,
                ],
                [
                    'name' => 'kingDiamonds',
                    'number' => 49,
                    'suit' => 'diamond',
                    'rank' => 6,
                    'twinCardNumber' => 53,
                    'img' => '/images/svg/king_of_diamonds.svg',
                    'score' => 16,
                ],
                [
                    'name' => 'kingHearts',
                    'number' => 50,
                    'suit' => 'heart',
                    'rank' => 6,
                    'twinCardNumber' => 54,
                    'img' => '/images/svg/king_of_hearts.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'kingSpades',
                    'number' => 51,
                    'suit' => 'spade',
                    'rank' => 6,
                    'twinCardNumber' => 55,
                    'img' => '/images/svg/king_of_spades.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'kingClubs',
                    'number' => 52,
                    'suit' => 'club',
                    'rank' => 6,
                    'twinCardNumber' => 56,
                    'img' => '/images/svg/king_of_clubs.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'kingDiamonds',
                    'number' => 53,
                    'suit' => 'diamond',
                    'rank' => 6,
                    'twinCardNumber' => 49,
                    'img' => '/images/svg/king_of_diamonds.svg',
                    'score' => 16,
                ],
                [
                    'name' => 'kingHearts',
                    'number' => 54,
                    'suit' => 'heart',
                    'rank' => 6,
                    'twinCardNumber' => 50,
                    'img' => '/images/svg/king_of_hearts.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'kingSpades',
                    'number' => 55,
                    'suit' => 'spade',
                    'rank' => 6,
                    'twinCardNumber' => 51,
                    'img' => '/images/svg/king_of_spades.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'kingClubs',
                    'number' => 56,
                    'suit' => 'club',
                    'rank' => 6,
                    'twinCardNumber' => 52,
                    'img' => '/images/svg/king_of_clubs.svg',
                    'score' => 6,
                ],
                [
                    'name' => 'tenHearts',
                    'number' => 26,
                    'suit' => 'heart',
                    'rank' => 7,
                    'twinCardNumber' => 30,
                    'img' => '/images/svg/10_of_hearts.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'tenSpades',
                    'number' => 27,
                    'suit' => 'spade',
                    'rank' => 7,
                    'twinCardNumber' => 31,
                    'img' => '/images/svg/10_of_spades.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'tenClubs',
                    'number' => 28,
                    'suit' => 'club',
                    'rank' => 7,
                    'twinCardNumber' => 32,
                    'img' => '/images/svg/10_of_clubs.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'tenDiamonds',
                    'number' => 29,
                    'suit' => 'diamond',
                    'rank' => 7,
                    'twinCardNumber' => 25,
                    'img' => '/images/svg/10_of_diamonds.svg',
                    'score' => 17,
                ],
                [
                    'name' => 'tenHearts',
                    'number' => 30,
                    'suit' => 'heart',
                    'rank' => 7,
                    'twinCardNumber' => 26,
                    'img' => '/images/svg/10_of_hearts.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'tenSpades',
                    'number' => 31,
                    'suit' => 'spade',
                    'rank' => 7,
                    'twinCardNumber' => 27,
                    'img' => '/images/svg/10_of_spades.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'tenClubs',
                    'number' => 32,
                    'suit' => 'club',
                    'rank' => 7,
                    'twinCardNumber' => 28,
                    'img' => '/images/svg/10_of_clubs.svg',
                    'score' => 7,
                ],
                [
                    'name' => 'oneDiamond',
                    'number' => 57,
                    'suit' => 'diamond',
                    'rank' => 8,
                    'twinCardNumber' => 61,
                    'img' => '/images/svg/ace_of_diamonds.svg',
                    'score' => 18,
                ],
                [
                    'name' => 'oneHeart',
                    'number' => 58,
                    'suit' => 'heart',
                    'rank' => 8,
                    'twinCardNumber' => 62,
                    'img' => '/images/svg/ace_of_hearts.svg',
                    'score' => 8,
                ],
                [
                    'name' => 'oneSpade',
                    'number' => 59,
                    'suit' => 'spade',
                    'rank' => 8,
                    'twinCardNumber' => 63,
                    'img' => '/images/svg/ace_of_spades.svg',
                    'score' => 8,
                ],
                [
                    'name' => 'oneClub',
                    'number' => 60,
                    'suit' => 'club',
                    'rank' => 8,
                    'twinCardNumber' => 64,
                    'img' => '/images/svg/ace_of_clubs.svg',
                    'score' => 8,
                ],
                [
                    'name' => 'oneHeart',
                    'number' => 62,
                    'suit' => 'heart',
                    'rank' => 8,
                    'twinCardNumber' => 58,
                    'img' => '/images/svg/ace_of_hearts.svg',
                    'score' => 8,
                ],
                [
                    'name' => 'oneSpade',
                    'number' => 63,
                    'suit' => 'spade',
                    'rank' => 8,
                    'twinCardNumber' => 59,
                    'img' => '/images/svg/ace_of_spades.svg',
                    'score' => 8,
                ],
                [
                    'name' => 'oneClub',
                    'number' => 64,
                    'suit' => 'club',
                    'rank' => 8,
                    'twinCardNumber' => 60,
                    'img' => '/images/svg/ace_of_clubs.svg',
                    'score' => 8,
                ],
            ],
            'playerCardPlayed' => [
                'name' => 'tenDiamonds',
                'number' => 25,
                'suit' => 'diamond',
                'rank' => 7,
                'twinCardNumber' => 29,
                'img' => '/images/svg/10_of_diamonds.svg',
                'score' => 17,
            ],
            'computerCardPlayed' => null,
            'handPlayer' => [
                [
                    'name' => 'sevenDiamonds',
                    'number' => 1,
                    'suit' => 'diamond',
                    'rank' => 1,
                    'twinCardNumber' => 5,
                    'img' => '/images/svg/7_of_diamonds.svg',
                    'score' => 11,
                ],
                [
                    'name' => 'sevenHearts',
                    'number' => 2,
                    'suit' => 'heart',
                    'rank' => 1,
                    'twinCardNumber' => 6,
                    'img' => '/images/svg/7_of_hearts.svg',
                    'score' => 1,
                ],
                [
                    'name' => 'sevenSpades',
                    'number' => 3,
                    'suit' => 'spade',
                    'rank' => 1,
                    'twinCardNumber' => 7,
                    'img' => '/images/svg/7_of_spades.svg',
                    'score' => 1,
                ],
                [
                    'name' => 'sevenClubs',
                    'number' => 4,
                    'suit' => 'club',
                    'rank' => 1,
                    'twinCardNumber' => 8,
                    'img' => '/images/svg/7_of_clubs.svg',
                    'score' => 1,
                ],
                [
                    'name' => 'sevenDiamonds',
                    'number' => 5,
                    'suit' => 'diamond',
                    'rank' => 1,
                    'twinCardNumber' => 1,
                    'img' => '/images/svg/7_of_diamonds.svg',
                    'score' => 11,
                ],
                [
                    'name' => 'sevenHearts',
                    'number' => 6,
                    'suit' => 'heart',
                    'rank' => 1,
                    'twinCardNumber' => 2,
                    'img' => '/images/svg/7_of_hearts.svg',
                    'score' => 1,
                ],
                [
                    'name' => 'sevenClubs',
                    'number' => 8,
                    'suit' => 'club',
                    'rank' => 1,
                    'twinCardNumber' => 4,
                    'img' => '/images/svg/7_of_clubs.svg',
                    'score' => 1,
                ],
                [
                    'name' => 'eightDiamonds',
                    'number' => 9,
                    'suit' => 'diamond',
                    'rank' => 2,
                    'twinCardNumber' => 13,
                    'img' => '/images/svg/8_of_diamonds.svg',
                    'score' => 12,
                ],
                [
                    'name' => 'eightHearts',
                    'number' => 10,
                    'suit' => 'heart',
                    'rank' => 2,
                    'twinCardNumber' => 14,
                    'img' => '/images/svg/8_of_hearts.svg',
                    'score' => 2,
                ]
            ],
            'handComputer' => [
                [
                    'name' => 'jackSpades',
                    'number' => 35,
                    'suit' => 'spade',
                    'rank' => 4,
                    'twinCardNumber' => 39,
                    'img' => '/images/svg/jack_of_spades.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'jackSpades',
                    'number' => 39,
                    'suit' => 'spade',
                    'rank' => 4,
                    'twinCardNumber' => 35,
                    'img' => '/images/svg/jack_of_spades.svg',
                    'score' => 4,
                ],
                [
                    'name' => 'queenDiamonds',
                    'number' => 41,
                    'suit' => 'diamond',
                    'rank' => 5,
                    'twinCardNumber' => 45,
                    'img' => '/images/svg/queen_of_diamonds.svg',
                    'score' => 15,
                ],
                [
                    'name' => 'oneDiamond',
                    'number' => 61,
                    'suit' => 'diamond',
                    'rank' => 8,
                    'twinCardNumber' => 57,
                    'img' => '/images/svg/ace_of_diamonds.svg',
                    'score' => 18,
                ],
                [
                    'name' => 'eightSpades',
                    'number' => 11,
                    'suit' => 'spade',
                    'rank' => 2,
                    'twinCardNumber' => 15,
                    'img' => '/images/svg/8_of_spades.svg',
                    'score' => 2,
                ],
                [
                    'name' => 'eightClubs',
                    'number' => 12,
                    'suit' => 'club',
                    'rank' => 2,
                    'twinCardNumber' => 16,
                    'img' => '/images/svg/8_of_clubs.svg',
                    'score' => 2,
                ],
                [
                    'name' => 'eightDiamonds',
                    'number' => 13,
                    'suit' => 'diamond',
                    'rank' => 2,
                    'twinCardNumber' => 9,
                    'img' => '/images/svg/8_of_diamonds.svg',
                    'score' => 12,
                ],
                [
                    'name' => 'eightHearts',
                    'number' => 14,
                    'suit' => 'heart',
                    'rank' => 2,
                    'twinCardNumber' => 10,
                    'img' => '/images/svg/8_of_hearts.svg',
                    'score' => 2,
                ],
                [
                    'name' => 'eightSpades',
                    'number' => 15,
                    'suit' => 'spade',
                    'rank' => 2,
                    'twinCardNumber' => 11,
                    'img' => '/images/svg/8_of_spades.svg',
                    'score' => 2,
                ],
                [
                    'name' => 'eightClubs',
                    'number' => 16,
                    'suit' => 'club',
                    'rank' => 2,
                    'twinCardNumber' => 12,
                    'img' => '/images/svg/8_of_clubs.svg',
                    'score' => 2,
                ],
            ],
            'trickPlayer' => [],
            'trickComputer' => [],
            'declarationsAvailablePlayer' => [],
            'declarationsAvailableComputer' => [],
            'score' => [
                'player1' => 0,
                'player2' => 0,
                'declarationsListP1' => [],
                'declarationsListP2' => [],
                'round' => 1,
                'previousRounds' => []
            ],
            'difficulty' => 'expert',
        ];

        $card_player = [
            'name' => 'tenDiamonds',
            'number' => 25,
            'suit' => 'diamond',
            'rank' => 7,
            'twinCardNumber' => 29,
            'img' => '/images/svg/10_of_diamonds.svg',
            'score' => 17,
        ];

        $card_to_evaluate = [
            'name' => 'oneDiamond',
            'number' => 61,
            'suit' => 'diamond',
            'rank' => 8,
            'twinCardNumber' => 57,
            'img' => '/images/svg/ace_of_diamonds.svg',
            'score' => 18,
        ];

        $Value = new Value;
        $Card_to_evaluate = $Value->valueCard($card_to_evaluate, $data['stack'], $data['handComputer'], $data['trump']);

        

        var_dump($Consequences->consequencesCard($Card_to_evaluate, $data, $card_player));
    }


    








    // $data = [
    //     'init' => true,
    //     'playFirst' => 'player',
    //     'stage' => 'draw',
    //     'trump' => [
    //         'name' => 'sevenDiamonds',
    //         'number' => 1,
    //         'suit' => 'diamond',
    //         'rank' => 1,
    //         'twinCardNumber' => 5,
    //         'img' => '/images/svg/7_of_diamonds.svg',
    //         'score' => 11,
    //     ],
    //     'stack' => [
    //         [
    //             'name' => 'sevenHearts',
    //             'number' => 2,
    //             'suit' => 'heart',
    //             'rank' => 1,
    //             'twinCardNumber' => 6,
    //             'img' => '/images/svg/7_of_hearts.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'sevenSpades',
    //             'number' => 3,
    //             'suit' => 'spade',
    //             'rank' => 1,
    //             'twinCardNumber' => 7,
    //             'img' => '/images/svg/7_of_spades.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'sevenClubs',
    //             'number' => 4,
    //             'suit' => 'club',
    //             'rank' => 1,
    //             'twinCardNumber' => 8,
    //             'img' => '/images/svg/7_of_clubs.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'sevenDiamonds',
    //             'number' => 5,
    //             'suit' => 'diamond',
    //             'rank' => 1,
    //             'twinCardNumber' => 1,
    //             'img' => '/images/svg/7_of_diamonds.svg',
    //             'score' => 11,
    //         ],
    //         [
    //             'name' => 'sevenHearts',
    //             'number' => 6,
    //             'suit' => 'heart',
    //             'rank' => 1,
    //             'twinCardNumber' => 2,
    //             'img' => '/images/svg/7_of_hearts.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'sevenSpades',
    //             'number' => 7,
    //             'suit' => 'spade',
    //             'rank' => 1,
    //             'twinCardNumber' => 3,
    //             'img' => '/images/svg/7_of_spades.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'sevenClubs',
    //             'number' => 8,
    //             'suit' => 'club',
    //             'rank' => 1,
    //             'twinCardNumber' => 4,
    //             'img' => '/images/svg/7_of_clubs.svg',
    //             'score' => 1,
    //         ],
    //         [
    //             'name' => 'eightDiamonds',
    //             'number' => 9,
    //             'suit' => 'diamond',
    //             'rank' => 2,
    //             'twinCardNumber' => 13,
    //             'img' => '/images/svg/8_of_diamonds.svg',
    //             'score' => 12,
    //         ],
    //         [
    //             'name' => 'eightHearts',
    //             'number' => 10,
    //             'suit' => 'heart',
    //             'rank' => 2,
    //             'twinCardNumber' => 14,
    //             'img' => '/images/svg/8_of_hearts.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'eightSpades',
    //             'number' => 11,
    //             'suit' => 'spade',
    //             'rank' => 2,
    //             'twinCardNumber' => 15,
    //             'img' => '/images/svg/8_of_spades.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'eightClubs',
    //             'number' => 12,
    //             'suit' => 'club',
    //             'rank' => 2,
    //             'twinCardNumber' => 16,
    //             'img' => '/images/svg/8_of_clubs.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'eightDiamonds',
    //             'number' => 13,
    //             'suit' => 'diamond',
    //             'rank' => 2,
    //             'twinCardNumber' => 9,
    //             'img' => '/images/svg/8_of_diamonds.svg',
    //             'score' => 12,
    //         ],
    //         [
    //             'name' => 'eightHearts',
    //             'number' => 14,
    //             'suit' => 'heart',
    //             'rank' => 2,
    //             'twinCardNumber' => 10,
    //             'img' => '/images/svg/8_of_hearts.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'eightSpades',
    //             'number' => 15,
    //             'suit' => 'spade',
    //             'rank' => 2,
    //             'twinCardNumber' => 11,
    //             'img' => '/images/svg/8_of_spades.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'eightClubs',
    //             'number' => 16,
    //             'suit' => 'club',
    //             'rank' => 2,
    //             'twinCardNumber' => 12,
    //             'img' => '/images/svg/8_of_clubs.svg',
    //             'score' => 2,
    //         ],
    //         [
    //             'name' => 'nineDiamonds',
    //             'number' => 17,
    //             'suit' => 'diamond',
    //             'rank' => 3,
    //             'twinCardNumber' => 21,
    //             'img' => '/images/svg/9_of_diamonds.svg',
    //             'score' => 13,
    //         ],
    //         [
    //             'name' => 'nineHearts',
    //             'number' => 18,
    //             'suit' => 'heart',
    //             'rank' => 3,
    //             'twinCardNumber' => 22,
    //             'img' => '/images/svg/9_of_hearts.svg',
    //             'score' => 3,
    //         ],
    //         [
    //             'name' => 'nineSpades',
    //             'number' => 19,
    //             'suit' => 'spade',
    //             'rank' => 3,
    //             'twinCardNumber' => 23,
    //             'img' => '/images/svg/9_of_spades.svg',
    //             'score' => 3,
    //         ],
    //         [
    //             'name' => 'nineClubs',
    //             'number' => 20,
    //             'suit' => 'club',
    //             'rank' => 3,
    //             'twinCardNumber' => 24,
    //             'img' => '/images/svg/9_of_clubs.svg',
    //             'score' => 3,
    //         ],
    //         [
    //             'name' => 'nineDiamonds',
    //             'number' => 21,
    //             'suit' => 'diamond',
    //             'rank' => 3,
    //             'twinCardNumber' => 17,
    //             'img' => '/images/svg/9_of_diamonds.svg',
    //             'score' => 13,
    //         ],
    //         [
    //             'name' => 'nineHearts',
    //             'number' => 22,
    //             'suit' => 'heart',
    //             'rank' => 3,
    //             'twinCardNumber' => 18,
    //             'img' => '/images/svg/9_of_hearts.svg',
    //             'score' => 3
    //         ],
    //         [
    //             'name' => 'nineSpades',
    //             'number' => 23,
    //             'suit' => 'spade',
    //             'rank' => 3,
    //             'twinCardNumber' => 19,
    //             'img' => '/images/svg/9_of_spades.svg',
    //             'score' => 3
    //         ],
    //         [
    //             'name' => 'nineClubs',
    //             'number' => 24,
    //             'suit' => 'club',
    //             'rank' => 3,
    //             'twinCardNumber' => 20,
    //             'img' => '/images/svg/9_of_clubs.svg',
    //             'score' => 3,
    //         ],
    //         [
    //             'name' => 'jackDiamonds',
    //             'number' => 33,
    //             'suit' => 'diamond',
    //             'rank' => 4,
    //             'twinCardNumber' => 37,
    //             'img' => '/images/svg/jack_of_diamonds.svg',
    //             'score' => 14,
    //         ],
    //         [
    //             'name' => 'jackHearts',
    //             'number' => 34,
    //             'suit' => 'heart',
    //             'rank' => 4,
    //             'twinCardNumber' => 38,
    //             'img' => '/images/svg/jack_of_hearts.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'jackSpades',
    //             'number' => 35,
    //             'suit' => 'spade',
    //             'rank' => 4,
    //             'twinCardNumber' => 39,
    //             'img' => '/images/svg/jack_of_spades.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'jackClubs',
    //             'number' => 36,
    //             'suit' => 'club',
    //             'rank' => 4,
    //             'twinCardNumber' => 40,
    //             'img' => '/images/svg/jack_of_clubs.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'jackDiamonds',
    //             'number' => 37,
    //             'suit' => 'diamond',
    //             'rank' => 4,
    //             'twinCardNumber' => 33,
    //             'img' => '/images/svg/jack_of_diamonds.svg',
    //             'score' => 14,
    //         ],
    //         [
    //             'name' => 'jackHearts',
    //             'number' => 38,
    //             'suit' => 'heart',
    //             'rank' => 4,
    //             'twinCardNumber' => 34,
    //             'img' => '/images/svg/jack_of_hearts.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'jackSpades',
    //             'number' => 39,
    //             'suit' => 'spade',
    //             'rank' => 4,
    //             'twinCardNumber' => 35,
    //             'img' => '/images/svg/jack_of_spades.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'jackClubs',
    //             'number' => 40,
    //             'suit' => 'club',
    //             'rank' => 4,
    //             'twinCardNumber' => 36,
    //             'img' => '/images/svg/jack_of_clubs.svg',
    //             'score' => 4,
    //         ],
    //         [
    //             'name' => 'queenDiamonds',
    //             'number' => 41,
    //             'suit' => 'diamond',
    //             'rank' => 5,
    //             'twinCardNumber' => 45,
    //             'img' => '/images/svg/queen_of_diamonds.svg',
    //             'score' => 15,
    //         ],
    //         [
    //             'name' => 'queenHearts',
    //             'number' => 42,
    //             'suit' => 'heart',
    //             'rank' => 5,
    //             'twinCardNumber' => 46,
    //             'img' => '/images/svg/queen_of_hearts.svg',
    //             'score' => 5,
    //         ],
    //         [
    //             'name' => 'queenSpades',
    //             'number' => 43,
    //             'suit' => 'spade',
    //             'rank' => 5,
    //             'twinCardNumber' => 47,
    //             'img' => '/images/svg/queen_of_spades.svg',
    //             'score' => 5
    //         ],
    //         [
    //             'name' => 'queenClubs',
    //             'number' => 44,
    //             'suit' => 'club',
    //             'rank' => 5,
    //             'twinCardNumber' => 48,
    //             'img' => '/images/svg/queen_of_clubs.svg',
    //             'score' => 5,
    //         ],
    //         [
    //             'name' => 'queenDiamonds',
    //             'number' => 45,
    //             'suit' => 'diamond',
    //             'rank' => 5,
    //             'twinCardNumber' => 41,
    //             'img' => '/images/svg/queen_of_diamonds.svg',
    //             'score' => 15,
    //         ],
    //         [
    //             'name' => 'queenHearts',
    //             'number' => 46,
    //             'suit' => 'heart',
    //             'rank' => 5,
    //             'twinCardNumber' => 42,
    //             'img' => '/images/svg/queen_of_hearts.svg',
    //             'score' => 5,
    //         ],
    //         [
    //             'name' => 'queenSpades',
    //             'number' => 47,
    //             'suit' => 'spade',
    //             'rank' => 5,
    //             'twinCardNumber' => 43,
    //             'img' => '/images/svg/queen_of_spades.svg',
    //             'score' => 5,
    //         ],
    //         [
    //             'name' => 'queenClubs',
    //             'number' => 48,
    //             'suit' => 'club',
    //             'rank' => 5,
    //             'twinCardNumber' => 44,
    //             'img' => '/images/svg/queen_of_clubs.svg',
    //             'score' => 5,
    //         ],
    //         [
    //             'name' => 'kingDiamonds',
    //             'number' => 49,
    //             'suit' => 'diamond',
    //             'rank' => 6,
    //             'twinCardNumber' => 53,
    //             'img' => '/images/svg/king_of_diamonds.svg',
    //             'score' => 16,
    //         ],
    //         [
    //             'name' => 'kingHearts',
    //             'number' => 50,
    //             'suit' => 'heart',
    //             'rank' => 6,
    //             'twinCardNumber' => 54,
    //             'img' => '/images/svg/king_of_hearts.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'kingSpades',
    //             'number' => 51,
    //             'suit' => 'spade',
    //             'rank' => 6,
    //             'twinCardNumber' => 55,
    //             'img' => '/images/svg/king_of_spades.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'kingClubs',
    //             'number' => 52,
    //             'suit' => 'club',
    //             'rank' => 6,
    //             'twinCardNumber' => 56,
    //             'img' => '/images/svg/king_of_clubs.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'kingDiamonds',
    //             'number' => 53,
    //             'suit' => 'diamond',
    //             'rank' => 6,
    //             'twinCardNumber' => 49,
    //             'img' => '/images/svg/king_of_diamonds.svg',
    //             'score' => 16,
    //         ],
    //         [
    //             'name' => 'kingHearts',
    //             'number' => 54,
    //             'suit' => 'heart',
    //             'rank' => 6,
    //             'twinCardNumber' => 50,
    //             'img' => '/images/svg/king_of_hearts.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'kingSpades',
    //             'number' => 55,
    //             'suit' => 'spade',
    //             'rank' => 6,
    //             'twinCardNumber' => 51,
    //             'img' => '/images/svg/king_of_spades.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'kingClubs',
    //             'number' => 56,
    //             'suit' => 'club',
    //             'rank' => 6,
    //             'twinCardNumber' => 52,
    //             'img' => '/images/svg/king_of_clubs.svg',
    //             'score' => 6,
    //         ],
    //         [
    //             'name' => 'tenDiamonds',
    //             'number' => 25,
    //             'suit' => 'diamond',
    //             'rank' => 7,
    //             'twinCardNumber' => 29,
    //             'img' => '/images/svg/10_of_diamonds.svg',
    //             'score' => 17,
    //         ],
    //         [
    //             'name' => 'tenHearts',
    //             'number' => 26,
    //             'suit' => 'heart',
    //             'rank' => 7,
    //             'twinCardNumber' => 30,
    //             'img' => '/images/svg/10_of_hearts.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'tenSpades',
    //             'number' => 27,
    //             'suit' => 'spade',
    //             'rank' => 7,
    //             'twinCardNumber' => 31,
    //             'img' => '/images/svg/10_of_spades.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'tenClubs',
    //             'number' => 28,
    //             'suit' => 'club',
    //             'rank' => 7,
    //             'twinCardNumber' => 32,
    //             'img' => '/images/svg/10_of_clubs.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'tenDiamonds',
    //             'number' => 29,
    //             'suit' => 'diamond',
    //             'rank' => 7,
    //             'twinCardNumber' => 25,
    //             'img' => '/images/svg/10_of_diamonds.svg',
    //             'score' => 17,
    //         ],
    //         [
    //             'name' => 'tenHearts',
    //             'number' => 30,
    //             'suit' => 'heart',
    //             'rank' => 7,
    //             'twinCardNumber' => 26,
    //             'img' => '/images/svg/10_of_hearts.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'tenSpades',
    //             'number' => 31,
    //             'suit' => 'spade',
    //             'rank' => 7,
    //             'twinCardNumber' => 27,
    //             'img' => '/images/svg/10_of_spades.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'tenClubs',
    //             'number' => 32,
    //             'suit' => 'club',
    //             'rank' => 7,
    //             'twinCardNumber' => 28,
    //             'img' => '/images/svg/10_of_clubs.svg',
    //             'score' => 7,
    //         ],
    //         [
    //             'name' => 'oneDiamond',
    //             'number' => 57,
    //             'suit' => 'diamond',
    //             'rank' => 8,
    //             'twinCardNumber' => 61,
    //             'img' => '/images/svg/ace_of_diamonds.svg',
    //             'score' => 18,
    //         ],
    //         [
    //             'name' => 'oneHeart',
    //             'number' => 58,
    //             'suit' => 'heart',
    //             'rank' => 8,
    //             'twinCardNumber' => 62,
    //             'img' => '/images/svg/ace_of_hearts.svg',
    //             'score' => 8,
    //         ],
    //         [
    //             'name' => 'oneSpade',
    //             'number' => 59,
    //             'suit' => 'spade',
    //             'rank' => 8,
    //             'twinCardNumber' => 63,
    //             'img' => '/images/svg/ace_of_spades.svg',
    //             'score' => 8,
    //         ],
    //         [
    //             'name' => 'oneClub',
    //             'number' => 60,
    //             'suit' => 'club',
    //             'rank' => 8,
    //             'twinCardNumber' => 64,
    //             'img' => '/images/svg/ace_of_clubs.svg',
    //             'score' => 8,
    //         ],
    //         [
    //             'name' => 'oneDiamond',
    //             'number' => 61,
    //             'suit' => 'diamond',
    //             'rank' => 8,
    //             'twinCardNumber' => 57,
    //             'img' => '/images/svg/ace_of_diamonds.svg',
    //             'score' => 18,
    //         ],
    //         [
    //             'name' => 'oneHeart',
    //             'number' => 62,
    //             'suit' => 'heart',
    //             'rank' => 8,
    //             'twinCardNumber' => 58,
    //             'img' => '/images/svg/ace_of_hearts.svg',
    //             'score' => 8,
    //         ],
    //         [
    //             'name' => 'oneSpade',
    //             'number' => 63,
    //             'suit' => 'spade',
    //             'rank' => 8,
    //             'twinCardNumber' => 59,
    //             'img' => '/images/svg/ace_of_spades.svg',
    //             'score' => 8,
    //         ],
    //         [
    //             'name' => 'oneClub',
    //             'number' => 64,
    //             'suit' => 'club',
    //             'rank' => 8,
    //             'twinCardNumber' => 60,
    //             'img' => '/images/svg/ace_of_clubs.svg',
    //             'score' => 8,
    //         ],
    //     ],
    //     'playerCardPlayed' => null,
    //     'computerCardPlayed' => null,
    //     'handPlayer' => [],
    //     'handComputer' => [],
    //     'trickPlayer' => [],
    //     'trickComputer' => [],
    //     'declarationsAvailablePlayer' => [],
    //     'declarationsAvailableComputer' => [],
    //     'score' => [
    //         'player1' => 0,
    //         'player2' => 0,
    //         'declarationsListP1' => [],
    //         'declarationsListP2' => [],
    //         'round' => 0,
    //         'previousRounds' => []
    //     ],
    // ];

}
